version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "JoshuaALawrence"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/cache"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "JoshuaALawrence"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/backup"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "JoshuaALawrence"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "JoshuaALawrence"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "JoshuaALawrence"
    labels:
      - "dependencies"
      - "docker"
